# Generated by Django 3.0.5 on 2020-05-19 10:00

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('user_id', models.CharField(max_length=9)),
                ('timezone', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ActivityPeriod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(default=datetime.datetime(2020, 5, 19, 10, 0, 6, 342288, tzinfo=utc))),
                ('end_time', models.DateTimeField(default=datetime.datetime(2020, 5, 19, 10, 0, 6, 342288, tzinfo=utc))),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.Employee')),
            ],
        ),
    ]
